version: '3'

services:
  app:
    build: .
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./data/app:/app:rw
    ports:
      - 3000:3000

  db:
    image: mongo:4.4.6-bionic
    volumes:
      - ./data/data/db:/data/db:rw
